name: Welcome New Contributors

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write  # Grant write permission to pull requests

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the contributor
        uses: actions/github-script@v7
        with:
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            const issueComment = 👋 Hello @${prAuthor}, thanks for opening your first pull request! We appreciate your contribution. 🎉;
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            });
